### ISSUE TITLE
NameError: name 'web_th' is not defined

### ISSUE THREAD

**Issue by tripmonger** [rkprojects/rpizw-dash-cam#2]
Hi, thanks for the interesting project. I followed your installation instructions on the Raspbian GNU/Linux 10 (buster). I am getting the following error when running the command:   ./run.sh

```
pi@raspberrypi:~/rpizw-dash-cam $ ./run.sh 
pi@raspberrypi:~/rpizw-dash-cam $ Traceback (most recent call last):
  File "main.py", line 162, in <module>
    web_th.join()
NameError: name 'web_th' is not defined
```

Any help would be appreciated. Thanks.

**Comment by rkprojects** [comment]
What's in the log file? Looks like some exception occurred even before creating web interface.
I have tested this project only on Raspbian GNU/Linux 9 (stretch).

**Comment by tripmonger** [comment]
Hi, here is the last 50 lines in the log file.

`  File "main.py", line 100, in <module>
    recorder.init()
  File "/home/pi/rpizw-dash-cam/src/recorder.py", line 149, in init
    _cfg = json.load(f)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

main:91:INFO:DashCam version 1.3.1
main:92:INFO:Deleting logs older than 2 days.
main:158:ERROR:Expecting value: line 1 column 1 (char 0)
main:159:ERROR:Traceback (most recent call last):
  File "main.py", line 100, in <module>
    recorder.init()
  File "/home/pi/rpizw-dash-cam/src/recorder.py", line 149, in init
    _cfg = json.load(f)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

main:91:INFO:DashCam version 1.3.1
main:92:INFO:Deleting logs older than 2 days.
main:158:ERROR:Expecting value: line 1 column 1 (char 0)
main:159:ERROR:Traceback (most recent call last):
  File "main.py", line 100, in <module>
    recorder.init()
  File "/home/pi/rpizw-dash-cam/src/recorder.py", line 149, in init
    _cfg = json.load(f)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`

Thanks.

**Comment by rkprojects** [comment]
Hi, thanks for log contents. I think what might have happened is when you first ran this application there must have been some exception while saving the config file (in records folder "cfg.json"). Now when every time you are restarting, config file loading fails.

To reproduce  this issue at my side, I will have to upgrade to "Raspbian Buster" which I will do someday while adding other features. 

If you would like to continue investigating this issue, I will suggest: delete the config file, run the app again (only once) and look into /share the log file, then lets see...

**Comment by tripmonger** [comment]
Hi, thanks. Deleting the cfg.json file, which was empty, seems to fix the error. Here is the log file results after run.sh:

```
main:91:INFO:DashCam version 1.3.1
main:92:INFO:Deleting logs older than 2 days.
main:101:INFO:Starting Recording


recorder:192:INFO:Initializing Pi Camera to 1920x1080 @ 30 fps
main:106:INFO:Starting Web Server


util:89:INFO:Found bluetoothd service version: 5.50, required: >= 5.50
main:115:INFO:Starting BLE GATT Server


ble_dcam:69:INFO:Registering GATT Service
dcam_service:451:INFO:Registering GATT application...
ble_dcam:78:INFO:Registering Advertisement
ble_dcam:85:INFO:DCam Service Online
dcam_service:422:INFO:GetManagedObjects
dcam_service:466:INFO:GATT application registered
dcam_advertisement:75:INFO:Advertisement registered

```
The cfg.json was not empty this time. Instead, it had the following content:

`{"rotation": 0, "cindex": 1, "max-files": 0, "n-loops": 0}`

Perhaps something in Raspbian 10 causes the config file to be blank on first run?

Thanks for your help in figuring out how to get run.sh to run.

**Comment by rkprojects** [comment]
Hi, thanks for the results. The simple way to figure out the root cause would be to do a clean reinstall of the application and check first log. But technically there is no difference between first run and running after deleting config file. It must be something else.

Now since the DashCam is working for you, enjoy...
